# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('timestamp', models.TimeField(auto_now=True)),
                ('updated', models.TimeField(auto_now_add=True)),
                ('parent', models.CharField(blank=True, max_length=40, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
